### ISSUE TITLE
Implementing authentication in wallet with seed and private key

### ISSUE THREAD

**Issue by Parabellum1905y** [AeneasPlatform/Aeneas#23]
At this [moment](https://github.com/AeneasPlatform/Aeneas/commit/ac5f2af5d7bc848cf79c3ac1a0734dd1c4036631) settings are hardcoded in the `settings.conf` file and main Application doesn't start despite you configure them.
We need to add an actor which will launch an application with parameters will be provided by the user in the client.

**Comment by Fly-Style** [comment]
Done.
