### ISSUE TITLE
How to run correctly two nodes of blockchain on the same PC?

### ISSUE THREAD

**Issue by Fly-Style** [AeneasPlatform/Aeneas#4]
When I was trying to launch two blockchain nodes for debugging, I got this message to my log from **second** node : 

`[warn] sbt server could not start because there's another instance of sbt running on this build.`
`[warn] Running multiple instances is unsupported`.

Also when that node trying to start its own actors, I got this exception : 

```[ERROR] [02/12/2018 14:09:48.355] [Aeneas-akka.actor.default-dispatcher-4] [akka://Aeneas/system/IO-TCP/selectors/$a/3] Bind failed for TCP channel on endpoint [/127.0.0.1:6886]```
```java.net.BindException: Address already in use``` .

So I want to understand: is that nodes are same or not? And does it safe way to run multiple nodes on one PC?

**Comment by Parabellum1905y** [comment]
fixed in PR # #7 ;
in nutshell - 127.0.0.1:6886 is address for REST API.

for running second node now you can run make command like this:
make run NETADDR="127.0.0.1:9999"
