### ISSUE TITLE
Blockchain explorer implementation

### ISSUE THREAD

**Issue by Fly-Style** [AeneasPlatform/Aeneas#57]
You should create UI component using Vue.js and internal Aeneas APIs for blockchain blocks explorer.
It should be a table where you will show next information (concrete order will be defined soon) : 

- Block creation timestamp
- Block's parent ID
- Block ID (it should be decoder using Base58 decoder)
- Count of transactions in this block.
- Account who was mined this block.

The number of blocks which are shown on one page should be hackable (options like 20, 50, 100 etc.).
The web-page should be done in cross-browser style and adopted for different screen resolutions.

**Comment by Parabellum1905y** [comment]
realized in the standard client
