### ISSUE TITLE
Proposal #2 : Transactions redesign. New transactions handling protocol. 

### ISSUE THREAD

**Issue by Fly-Style** [AeneasPlatform/Aeneas#73]
### Agenda
- Transactions overview
- Creation
- Validation

#### Transactions overview

Transaction is an atomic unit of valuable asset transfer from wallet to other wallet.
In **Aeneas** project we define **Ash** currency as the valuable asset.

Transaction consists from such elements :
  - Transfer amount
  - Sender's public key 
  - Receiver's public key
  - Fee
  
  For transactions manipulation we will use so called **Box abstraction**.  **Box** is an atomic unit at the lower level 
  of transfer protocol and generally it has signed and encrypted chunk of any information inside. 
  In our system we can use for creation so called **input** and **output**, where 
    - input is unit of valuable asset accuration
    - output is unit of valuable asset withdraw
 
#### Creation

Let's describe process of transaction creation step by step.
  - Wallet user inserts destination wallet's **public key** (in other word, address) and **transfer amount**.
  - Wallet user presses **Send** button.
  - System will initialize client transaction validation : 
    - Available balance should be checked : 
      - client should take the balance from the outlay records table is so called **publisher** block and save its value.
      - after this, client should calculate balance income and expense for each block in blockchain till the closest **publisher** block.
      - if the final sum will be less or equal to entered **transfer amount**, transaction is recognized as _invalid_.
      - else, it is recognized as _valid_, but _unconfirmed_. 
    - If client validation will fail, alert window with 'Value is not enough' message would be shown.
    - If client validation will be successful, go to the next step.
  - Wallet generates proposition **PublicKey25519Proposition** from current public key.
  - Wallet should creates an instance of **SimpleBoxTransaction**, where all transaction information should be stored.
  - This new box should be moved into so called **memory pool**, where all unconfirmed transactions are stored.
  - Balance should be decreased by the **transfer value plus fee value**.
  
  Note : **Memory pool** is **shared** between all active nodes.

**Comment by AeneasPM** [comment]
Hi to everyone! As we discussed with Parabellum, we should focus on starting up mainnet with working user transactions. The last item (confirmation) should be remove out from the current start. And after - the next step is to create good UTXO implementation.

**Comment by Fly-Style** [comment]
Removed confirmation item.
