### ISSUE TITLE
GrossBuch calculations

### ISSUE THREAD

**Issue by AeneasPM** [AeneasPlatform/Aeneas#91]
Need to check and implement main business-rules of Aeneas grossbuch.

Service transactions:
- 80 ASH goes to miner/block-generator as a reward for network processing;
- 10 ASH goes to public initiatives fund based on Aeneas platform;
- 8 ASH goes to master-node owners fund;
- 2 ASH goes to support Aeneas project development fund;

User transactions (check and complete calculations):
- When user generates a transaction, his balance should be **decreased** with a) sending amount (1st transaction) and b) fee transaction (2nd transaction);
- Receiver user account' balance should be **increased** with amount of input transaction;
- Block-generator should get input **fee transaction** and reward for block (service transaction as was mentioned above).

**Comment by Fly-Style** [comment]
fixed in #92, closed.
